# File generated with docstub

import locale
import logging
import os
import pprint
import re
import sys
from collections.abc import Callable, Iterable, Iterator, MutableMapping
from pathlib import Path
from types import ModuleType
from typing import Any, Literal, get_args

import numpy as np
from _typeshed import Incomplete

_log: Incomplete

ScaleKeyword: Incomplete

def _make_validate_choice(
    accepted_values: Iterable, allow_none: bool = ..., typeof: type = ...
) -> Callable | None: ...
def _make_validate_choice_regex(
    accepted_values: Iterable, accepted_values_regex: Iterable, allow_none: bool = ...
) -> Callable: ...
def _validate_positive_int(value: Incomplete) -> None: ...
def _validate_float(value: Incomplete) -> None: ...
def _validate_str(value: Incomplete) -> None: ...
def _validate_probability(value: Incomplete) -> float: ...
def _validate_rounding(value: int | str | None) -> str | int | None: ...
def _validate_boolean(value: Incomplete) -> None: ...
def _add_none_to_validator(base_validator: Incomplete) -> None: ...
def _validate_stats_module(value: str | ModuleType) -> str | ModuleType: ...
def _validate_bokeh_marker(value: Incomplete) -> None: ...
def _validate_backend(value: Incomplete) -> None: ...
def make_iterable_validator(
    scalar_validator: Incomplete,
    length: Incomplete = ...,
    allow_none: Incomplete = ...,
    allow_auto: Incomplete = ...,
) -> Callable: ...

_validate_float_or_none: Incomplete
_validate_positive_int_or_none: Incomplete
_validate_dims: Incomplete

defaultParams: Incomplete

class RcParams(MutableMapping):

    validate: Incomplete

    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def __setitem__(self, key: Incomplete, val: Incomplete) -> None: ...
    def __getitem__(self, key: Incomplete) -> None: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def clear(self) -> None: ...
    def pop(self, key: Incomplete, default: Incomplete = ...) -> None: ...
    def popitem(self) -> tuple[Any, Any]: ...
    def setdefault(self, key: Incomplete, default: Incomplete = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def find_all(self, pattern: Incomplete) -> None: ...
    def copy(self) -> None: ...

def get_arviz_rcfile() -> None: ...
def read_rcfile(fname: Incomplete) -> None: ...
def rc_params(ignore_files: Incomplete = ...) -> None: ...

rcParams: Incomplete

class rc_context:
    def __init__(self, rc: dict | None = ..., fname: str | None = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: Incomplete, exc_value: Incomplete, exc_tb: Incomplete
    ) -> None: ...
