# File generated with docstub

import numpy as np
from _typeshed import Incomplete
from xarray import DataTree

from arviz_base import from_dict

def generate_base_data(seed: Incomplete = ...) -> None: ...
def datatree(seed: Incomplete = ...) -> None: ...
def datatree2(seed: Incomplete = ...) -> None: ...
def datatree3(seed: Incomplete = ...) -> None: ...
def datatree_binary(seed: Incomplete = ...) -> None: ...
def datatree_regression(seed: Incomplete = ...) -> None: ...
def datatree_4d(seed: Incomplete = ...) -> None: ...
def datatree_sample(seed: Incomplete = ...) -> None: ...
def cmp() -> None: ...
def fake_dt() -> None: ...
def datatree_censored(seed: Incomplete = ...) -> None: ...
def check_multiple_attrs(
    test_dict: dict[str, list[str]], parent: DataTree
) -> list[str | tuple[str, str]]: ...
