# File generated with docstub

import typing
import warnings
from collections.abc import Callable, Mapping, Sequence
from typing import Any

from xarray import Dataset, DataTree

from arviz_base.rcparams import defaultParams, rcParams

def validate_sample_dims(
    sample_dims: str | Sequence[str] | None, data: Dataset | DataTree | None = ...
) -> list[str]: ...
def validate_dims_chain_draw_axis(dims, data=...) -> tuple[list, int | None, int]: ...
def validate_dict_argument(
    dict_arg: Mapping[str, Any] | None,
    func_arg: tuple[Callable, str] | None | None = ...,
    *,
    valid_keys: Sequence[str] | None | None = ...
) -> dict[str, Any]: ...
def validate_ci_prob(prob: float | None) -> float: ...
def validate_prob(prob: float, allow_0: bool = ...) -> float: ...
def validate_or_use_rcparam(arg_in: Any, rckey: str) -> Any: ...
